name: flutter_arch
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # State
  provider: ^4.3.2+2

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES
  webview_flutter: ^0.3.22+1
  flutter_webview_plugin: ^0.3.11
  device_info: ^0.4.2+7
  package_info: ^0.4.3
  quiver: ^2.1.3
  #  connectivity: ^0.4.3+6

  # Data
  #  json_annotation: ^2.4.0
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  shared_preferences: 0.5.10
  # 本地json对象存储
  localstorage: ^3.0.2+5

  # Html Encoder/Decoder
  html_unescape: ^1.0.2
  # 解析html标签
  flutter_html: ^1.0.2

  # 判断list是否相等
  collection: ^1.14.13
  #  crypto: ^2.0.6

  # UI
  oktoast: ^2.3.2
  pull_to_refresh: ^1.6.1
  flutter_swiper: ^1.1.6
  #  cached_network_image: ^1.1.1
  cached_network_image: ^2.3.1
  # 类iOS侧滑菜单
  flutter_slidable: ^0.5.7
  # 谁用谁闪亮
  shimmer: ^1.1.1
  # 识别图片的主要颜色
  #  palette_generator: ^0.2.0
  # 更新展示支持mark_down
  flutter_markdown: ^0.4.4
  flare_flutter: ^2.0.6

  # third_app
  # 启动第三方app
  url_launcher: ^5.1.6
  share: 0.6.2+1 #分享
  launch_review: ^2.0.0
  open_file: ^3.0.1

  # android权限弹窗
  #  permission_handler: ^3.2.2

  # 上报 目前问题比较多
#  flutter_bugly: 0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

#  build_runner: ^1.6.2
#  json_serializable: ^3.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: kuaile # 站酷 快乐字体  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
  assets:
    - assets/images/
    - assets/animations/

flutter_intl:
  enabled: true
